@startuml
title boostrap
namespace boostrap {
    class boostrap {
        + NewServer()
    }
    class Server {
        + Start()
        + WaitUntilCompletion()
    }
}

boostrap.boostrap --> boostrap.Server 
@enduml